In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
sns.get_dataset_names()
diamonds_df = sns.load_dataset("diamonds")
diamonds_df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
X = diamonds_df.drop(["price"], axis=1)
Y = diamonds_df["price"]

In [ ]:
X.head()
Y.head()

0    326
1    326
2    327
3    334
4    335
Name: price, dtype: int64

In [ ]:
numerical = X.drop(["cut", "color", "clarity"], axis=1)
numerical.head()
categorical = X.filter(['cut', 'color', 'clarity'])
categorical.head()

       cut color clarity
0    Ideal     E     SI2
1  Premium     E     SI1
2     Good     E     VS1
3  Premium     I     VS2
4     Good     J     SI2

In [ ]:
cat_numerical = pd.get_dummies(categorical,drop_first=True)
cat_numerical.head()

,cut_Premium,cut_Very Good,cut_Good,cut_Fair,color_E,color_F,color_G,color_H,color_I,color_J,clarity_VVS1,clarity_VVS2,clarity_VS1,clarity_VS2,clarity_SI1,clarity_SI2,clarity_I1
0,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False
1,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,False
3,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
4,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False

In [ ]:
X = pd.concat([numerical, cat_numerical], axis = 1)
X.head()

,carat,depth,table,x,y,z,cut_Premium,cut_Very Good,cut_Good,cut_Fair,...,color_H,color_I,color_J,clarity_VVS1,clarity_VVS2,clarity_VS1,clarity_VS2,clarity_SI1,clarity_SI2,clarity_I1
0,0.23,61.5,55.0,3.95,3.98,2.43,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,0.21,59.8,61.0,3.89,3.84,2.31,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,0.23,56.9,65.0,4.05,4.07,2.31,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
3,0.29,62.4,58.0,4.20,4.23,2.63,True,False,False,False,...,False,True,False,False,False,False,True,False,False,False
4,0.31,63.3,58.0,4.34,4.35,2.75,False,False,True,False,...,False,False,True,False,False,False,False,False,True,False

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y,
test_size=0.20, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #scaling the training set
X_test = sc.transform(X_test) #scaling the test set

In [ ]:
from sklearn.linear_model import LinearRegression
# training the algorithm
lin_reg = LinearRegression()
regressor = lin_reg.fit(X_train, y_train)
# making predictions on test set
y_pred = regressor.predict(X_test)

In [ ]:
from sklearn import metrics
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

Mean Absolute Error:  737.4354677843592
Mean Squared Error:  1248486.7135639722
Root Mean Squared Error:  1117.3570215307068
R2:  0.9212394719973422

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=5)
regressor = knn_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [ ]:
from sklearn import metrics
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

Mean Absolute Error:  1686.3554788809954
Mean Squared Error:  9971159.681983663
Root Mean Squared Error:  3157.7143129142737
R2:  0.3709714386066588

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(random_state=42, n_estimators=500)
regressor = rf_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [ ]:
from sklearn import metrics
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

Mean Absolute Error:  1686.3554788809954
Mean Squared Error:  9971159.681983663
Root Mean Squared Error:  3157.7143129142737
R2:  0.3709714386066588

In [ ]:
from sklearn import svm
svm_reg = svm.SVR()
regressor = svm_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [ ]:
from sklearn import metrics
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Mean Squared Error: ", metrics.mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("R2: ", metrics.r2_score(y_test, y_pred))

Mean Absolute Error:  1686.3554788809954
Mean Squared Error:  9971159.681983663
Root Mean Squared Error:  3157.7143129142737
R2:  0.3709714386066588

In [ ]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(regressor, X, Y, cv=5, scoring="neg_mean_absolute_error"))

[-1876.30968809 -4506.9321919  -6454.73902476 -2452.99594683
 -1556.56140729]

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(random_state=42, n_estimators=100)
regressor = rf_reg.fit(X_train, y_train)
single_record = sc.transform (X.values[100]. reshape(1, -1))
predicted_tip = regressor.predict(single_record)
print(predicted_tip)

[2781.22]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(